### ISSUE TITLE
Start populating ruleset on an opt-in basis

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-https-everywhere-ruleset#2]
For the 4/22-5/6 SecureDrop sprint, we've agreed that we want to continue news organization outreach, and start populating our prod ruleset with orgs that opt into initial pilot use of said ruleset in Tor Browser alphas/betas/prod. @emkll will be point on the first ruleset update made by someone other than @redshiftzero  :). @eloquence is continued point for news org outreach.

**Comment by redshiftzero** [comment]
Next org to onboard: The Intercept

We've also got some more feedback on the URL scheme, and let's just switch to option C while it's still early days, i.e. `theintercept.securedrop.tor.onion`, i.e. in the next ruleset release:

* Add redirect for `theintercept.securedrop.tor.onion` to the appropriate source interface
* Add redirect for `lucyparsonslabs.securedrop.tor.onion` to the appropriate source interface
* Leave in-place redirect for `lucyparsonslabs.com.securedrop.tor.onion` to the appropriate source interface for now since folks are using this to test
